name: 'publiccode-version-action'
description: 'Action description'
author: 'italia'

outputs:
  version:
    description: 'New version of softwareVersion in publiccode.yml'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'white'
